# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hiii guys from the Github Actions I wish you a very good day!
      
    - name: Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew assembleRelease"
        
    - name: Sign Android release
      uses: r0adkll/sign-android-release@v1
      with:
        # The directory to find your release to sign
        releaseDirectory: "./app/build/outputs/apk/release"
        # The key used to sign your release in base64 encoded format
        signingKeyBase64: ${{ secrets.BASE_64_SIGNING_KEY }}
        # The key alias
        alias: ${{ secrets.ALIAS }}
        # The password to the keystore
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        
